include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    annotate_overrides: true
    avoid_init_to_null: true
    constant_identifier_names: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    use_function_type_syntax_for_parameters: true
    valid_regexps: true
    close_sinks: true
    cancel_subscriptions: true
    throw_in_finally: true
    avoid_void_async: true
    recursive_getters: true
    package_api_docs: true
