import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/app_constants.dart';
import 'design_system/palette.dart';
import 'design_system/tbp_theme.dart';
import 'features/collective_session/presentation/widgets/collective_stream_box.dart';
import 'features/collective_session/presentation/widgets/contribution_form.dart';
import 'features/collective_session/presentation/widgets/session_timer.dart';
import 'features/collective_session/presentation/widgets/instructions_section.dart';
import 'features/collective_session/presentation/bloc/collective_session_bloc.dart';
import 'injected_container.dart' as di;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Supabase.initialize(
    url: AppConstants.supabaseUrl,
    anonKey: AppConstants.supabaseAnonKey,
  );
  
  await di.init();

  runApp(const TbpApp());
}

class TbpApp extends StatelessWidget {
  const TbpApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'The Bad Prompt',
      theme: TbpTheme.lightTheme,
      home: const LandingPage(),
      debugShowCheckedModeBanner: false,
    );
  }
}


class LandingPage extends StatelessWidget {
  const LandingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => di.sl<CollectiveSessionBloc>()..add(JoinSessionRequested('Anon')),
      child: const LandingPageView(),
    );
  }
}

class LandingPageView extends StatelessWidget {
  const LandingPageView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: const BoxDecoration(
          gradient: TbpPalette.backgroundGradient,
        ),
        child: SafeArea(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 40.0),
              child: Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 600), // Max width for clean look
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                       // 1. LOGO
                       Image.asset(
                         'assets/TBP_logo.png',
                         height: 80, 
                         errorBuilder: (c, o, s) => const Icon(Icons.broken_image, color: Colors.white, size: 50),
                       ),
                       const SizedBox(height: 32),

                       // 2. TEXT DESCRIPTION
                       const Text(
                         'An experience of collective and democratic art, generated by AI and human touch. Participate!\n\nThe Experience last 7 minutes, once the countdown is complete, wait for a maximum of 20 seconds before refreshing the page to view the results.\n\nThis is a BETA',
                         textAlign: TextAlign.center,
                         style: TextStyle(
                           color: TbpPalette.white,
                           fontSize: 16,
                           height: 1.5,
                           fontWeight: FontWeight.w500,
                         ),
                       ),
                       const SizedBox(height: 40),

                       // 3. COUNTDOWN & FAST FORWARD
                       const Center(child: SessionTimer()),
                       const SizedBox(height: 40),

                       // 4. STREAM BOX
                       const SizedBox(
                         height: 300, // Fixed height for stream
                         child: CollectiveStreamBox(),
                       ),
                       const SizedBox(height: 40),

                       // 5/6/7. INPUTS & SUBMIT (ContributionForm)
                       const ContributionForm(),
                       
                       const SizedBox(height: 64),

                       // 8. INSTRUCTIONS
                       const InstructionsSection(),
                       
                       const SizedBox(height: 40),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

